# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0 # don't link against any C headers
    goos: # build for these operating systems:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - arm64
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# https://github.com/goreleaser/nfpm; https://goreleaser.com/customization/nfpm/
nfpms:
  - maintainer: Steven Kalt
    homepage: https://github.com/skalt/git-cc
    description: a git extension to help write conventional commits
    license: "Indie Code Catalog Standard Deal >= 4.1"
    # symlinks:
      # /usr/local/bin/git-conventional-commit: /usr/local/bin/git-cc
    dependencies:
      - git
    formats:
      # - apk
      - deb
      - rpm
      # it'd be neat to have npm, gem, and pypi packages as well! 
