# GoReleaser config documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0 # don't link against any C headers
    goos: # build for these operating systems:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - arm64
      - amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms: # see https://goreleaser.com/customization/nfpm/
       # see also https://github.com/goreleaser/nfpm
  - maintainer: "Steven Kalt <steven@kalt.cloud>"
    homepage: &homepage "https://github.com/skalt/git-cc"
    description: &description "A git extension to help write conventional commits."
    license: &license "Polyform-Free-Trial-1.0.0 OR Polyform-Noncommercial-1.0.0 OR COMMERCIAL"

    # symlinks:
      # /usr/local/bin/git-conventional-commit: /usr/local/bin/git-cc
    dependencies: &dependencies
      - git
    formats:
      - deb
      - rpm
      - archlinux
      # it'd be neat to have nix, npm, gem, and pypi packages as well!
    provides:
      - git-cc
brews: # see https://goreleaser.com/customization/homebrew/
  - homepage: *homepage
    license: *license
    description: *description
    repository:
      owner: skalt
      name: homebrew-git-cc
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    download_strategy: CurlDownloadStrategy
    test: |
      system "#{bin}/git-cc --version"
    dependencies:
      - name: git
scoops: # see https://goreleaser.com/customization/scoop/
  - name: git-cc
    homepage: *homepage
    description: *description
    license: *license
    repository:
      owner: skalt
      name: scoop-git-cc
      branch: main
      token: "{{ .Env.SCOOP_GITHUB_TOKEN }}"
    depends: *dependencies
