# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  # hooks:
  #   # You may remove this if you don't use go modules.
  #   - go mod download
builds:
  - env:
      - CGO_ENABLED=0 # don't link against any C headers
    goos: # build for these operating systems:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
# https://github.com/goreleaser/nfpm; https://goreleaser.com/customization/nfpm/
nfpms:
  - maintainer: Steven Kalt
    # licence: UNLICENSED
    homepage: https://github.com/skalt/git-cc
    description: a git extension to help write conventional commits
    # waiting on changes related to https://github.com/goreleaser/goreleaser/issues/1829 
    # depends: [git]
    # symlinks:
    #   /usr/local/bin/git-cc: /usr/local/bin/git-conventional-commit
    formats:
      - apk
      - deb
      - rpm
      # it'd be neat to have npm, gem, and pypi packages as well! 